### ISSUE TITLE
Error : cannot import name horizon_occlusion_point

### ISSUE THREAD

**Issue by muzesh** [loicgasser/quantized-mesh-tile#24]
I'm now doing as you explained here. 

But I got error when I execute command at the python shell.

![image](https://user-images.githubusercontent.com/41287048/42803003-95ed2ad6-89df-11e8-82f9-6f370fca3b87.png)

I tried but couldn't solve the problem.

I really appreciate if you give me any help.

**Comment by loicgasser** [comment]
This seems like an installation issue as you can't import the module.

I only work on Unix systems so I don't really know your setup here.
Note that this library uses shapely and you will need to have GEO installed.
https://trac.osgeo.org/geos

Make sure the library is installed as module and that your python paths are correct.
