### ISSUE TITLE
Python3 official support?

### ISSUE THREAD

**Issue by swiss-knight** [loicgasser/quantized-mesh-tile#40]
Hi.

Did you plan to switch to a full Python3 support? (Or maybe it's already the case and I missed it?)    

Because I can read that:

> Quantized mesh tile requires Python >=2.7 (**not** including Python 3.x) and GEOS >= 3.3.

Here: https://quantized-mesh-tile.readthedocs.io/en/latest/index.html 

And Python 2 is now deprecated, I'm just wondering...
Thanks.

**Comment by loicgasser** [comment]
we already support python 3 but supported for 2 is still in the lib. I'll change the doc.

https://github.com/loicgasser/quantized-mesh-tile/blob/master/.travis.yml

I currently test 2.7, 3.6 and 3.7
I could drop 2.7 and add official support for 3.8.
